services:
  app:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      DB_DATABASE: travelly
      DB_ROOT_PASSWORD: root
      DB_USER: root
      DB_PASSWORD: W-Q!T9FYDiuX
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: pnpm dev

volumes:
  mysql-data:
