version: '3.8'
services:
  app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: triptrack
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: trip
      MYSQL_PASSWORD: track
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  mysql-data:
